class CurrentSquad:
    def __init__(self, gk, lb, cb1, cb2, rb, lm, cm1, cm2, rm, cam, st, sub1, sub2, sub3, sub4, sub5, sub6, id=None):
        self.gk = gk
        self.lb = lb
        self.cb1 = cb1
        self.cb2 = cb2
        self.rb = rb
        self.lm = lm
        self.cm1 = cm1
        self.cm2 = cm2
        self.rm = rm
        self.cam = cam
        self.st = st
        self.sub1 = sub1
        self.sub2 = sub2
        self.sub3 = sub3
        self.sub4 = sub4
        self.sub5 = sub5
        self.sub6 = sub6
        self.id = id